/*---------------------------------------------------------------------------------------------
 *  Copyright (c) 2026 Wang Chao. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import { appendFile, mkdir, readdir, readFile, rm, stat, writeFile } from 'node:fs/promises';
import { basename, dirname, join } from 'node:path';
import type { IArtifactEntryData, IArtifactFilter, IArtifactLineData, IArtifactPatchData } from '../sessions/services/artifacts/common/artifacts.js';
import type { ISessionEntry } from '../sessions/services/sessions/common/sessionsBridge.js';

/**
 * The project-scoped artifacts index (#13 P0): one append-only jsonl per scope,
 * folded on read (later lines with the same id override earlier ones; patch
 * lines merge in). The transcript is the truth — everything here except
 * export-path entries can be regenerated by rebuildArtifacts, which runs the
 * SAME extraction the live capture hooks run.
 */

export function artifactsFilePath(root: string, projectId?: string): string {
	return projectId ? join(root, 'projects', projectId, 'artifacts.jsonl') : join(root, 'artifacts.jsonl');
}

export async function appendArtifact(root: string, line: IArtifactLineData): Promise<void> {
	const file = artifactsFilePath(root, line.projectId);
	await mkdir(dirname(file), { recursive: true });
	await appendFile(file, `${JSON.stringify(line)}\n`, 'utf8');
}

/**
 * Read and fold one or more index files. With `projectId` only that project's
 * index is read; without it EVERY scope is read (the projectless index plus
 * all projects) — a sessionId-only filter can't know its scope up front.
 */
export async function listArtifacts(root: string, filter: IArtifactFilter = {}): Promise<readonly IArtifactEntryData[]> {
	const files: string[] = [];
	if (filter.projectId !== undefined) {
		files.push(artifactsFilePath(root, filter.projectId));
	} else {
		files.push(artifactsFilePath(root));
		for (const projectDir of await listDirectories(join(root, 'projects'))) {
			files.push(artifactsFilePath(root, projectDir));
		}
	}

	const folded = new Map<string, Record<string, unknown>>();
	for (const file of files) {
		let raw: string;
		try {
			raw = await readFile(file, 'utf8');
		} catch {
			continue;
		}
		for (const line of raw.split('\n')) {
			if (line.trim().length === 0) {
				continue;
			}
			let parsed: unknown;
			try {
				parsed = JSON.parse(line);
			} catch {
				continue;
			}
			if (typeof parsed !== 'object' || parsed === null || typeof (parsed as Record<string, unknown>)['id'] !== 'string') {
				continue;
			}
			const candidate = parsed as Record<string, unknown>;
			const id = candidate['id'] as string;
			// Entry and patch lines fold the same way: shallow-merge over the
			// previous state of the id. A patch that never meets its entry keeps
			// missing `kind` and is dropped below.
			folded.set(id, { ...folded.get(id), ...candidate });
		}
	}

	const entries: IArtifactEntryData[] = [];
	for (const candidate of folded.values()) {
		if (
			typeof candidate['kind'] !== 'string' ||
			typeof candidate['sessionId'] !== 'string' ||
			typeof candidate['title'] !== 'string' ||
			typeof candidate['createdAt'] !== 'string' ||
			typeof candidate['payload'] !== 'object' ||
			candidate['payload'] === null
		) {
			continue;
		}
		if (filter.sessionId !== undefined && candidate['sessionId'] !== filter.sessionId) {
			continue;
		}
		entries.push(candidate as unknown as IArtifactEntryData);
	}

	return entries.sort((a, b) => a.createdAt.localeCompare(b.createdAt) || a.id.localeCompare(b.id));
}

/**
 * The single extraction shared by the live capture hook (sessions:append) and
 * rebuildArtifacts — keeping them the same function is what guarantees the
 * index is always regenerable from the transcripts. Tolerates raw parsed jsonl
 * objects (rebuild feeds it unvalidated lines).
 */
export function extractArtifactsFromEntries(sessionId: string, projectId: string | undefined, entries: readonly ISessionEntry[]): readonly IArtifactLineData[] {
	const lines: IArtifactLineData[] = [];
	const projectField = projectId !== undefined ? { projectId } : {};

	for (const entry of entries) {
		if (entry.type === 'message' && typeof entry.id === 'string' && typeof entry.timestamp === 'string') {
			if (entry.role === 'plan' && entry.plan !== undefined && typeof entry.plan.title === 'string') {
				lines.push({
					id: `${sessionId}:${entry.id}`,
					kind: entry.plan.kind === 'walkthrough' ? 'walkthrough' : 'plan',
					sessionId,
					...projectField,
					title: entry.plan.title,
					createdAt: entry.timestamp,
					payload: { type: 'message', messageId: entry.id },
				});
			}
			if (entry.role === 'ui' && entry.ui !== undefined && typeof entry.ui.title === 'string') {
				lines.push({
					id: `${sessionId}:${entry.id}`,
					kind: 'ui-card',
					sessionId,
					...projectField,
					title: entry.ui.title,
					createdAt: entry.timestamp,
					payload: { type: 'message', messageId: entry.id },
				});
			}
			continue;
		}

		if (entry.type === 'planState' && entry.planState === 'superseded' && typeof entry.messageId === 'string') {
			const patch: IArtifactPatchData = { id: `${sessionId}:${entry.messageId}`, superseded: true, ...projectField };
			lines.push(patch);
		}
	}

	return lines;
}

/**
 * Drop and regenerate one scope's index (projectId absent = the projectless
 * scope) by scanning its session transcripts, then its media dirs for stored
 * table csvs.
 *
 * Known limitations (accepted, documented): export-kind entries reference
 * paths OUTSIDE the data root that exist only in the index — a rebuild loses
 * them. Rebuilt table entries get their title from the csv file name (the
 * sanitized form of the original) and their createdAt from the file's mtime.
 */
export async function rebuildArtifacts(root: string, projectId?: string): Promise<void> {
	const file = artifactsFilePath(root, projectId);
	// Export entries point OUTSIDE the data root — the index is their only
	// record, so a rebuild carries them over instead of wiping them (the P1
	// panel rebuilds on every mount; dropping exports there would erase the
	// very records #13 set out to keep).
	const preserved: string[] = [];
	try {
		for (const line of (await readFile(file, 'utf8')).split('\n')) {
			if (line.trim() === '') {
				continue;
			}
			try {
				const parsed = JSON.parse(line) as { kind?: unknown };
				if (parsed !== null && typeof parsed === 'object' && parsed.kind === 'export') {
					preserved.push(line);
				}
			} catch {
				// Torn line — nothing to preserve from it.
			}
		}
	} catch {
		// No existing index — nothing to preserve.
	}
	await rm(file, { force: true });

	const sessionsDir = projectId !== undefined ? join(root, 'projects', projectId, 'sessions') : join(root, 'sessions');
	const lines: IArtifactLineData[] = [];

	for (const sessionFile of [...(await listFiles(sessionsDir, '.jsonl'))].sort()) {
		const sessionId = basename(sessionFile, '.jsonl');
		let raw: string;
		try {
			raw = await readFile(sessionFile, 'utf8');
		} catch {
			continue;
		}
		const entries: ISessionEntry[] = [];
		for (const line of raw.split('\n')) {
			if (line.trim().length === 0) {
				continue;
			}
			try {
				const parsed = JSON.parse(line) as unknown;
				if (typeof parsed === 'object' && parsed !== null) {
					entries.push(parsed as ISessionEntry);
				}
			} catch {
				// A torn/corrupt line loses at most its own artifact — keep scanning.
			}
		}
		lines.push(...extractArtifactsFromEntries(sessionId, projectId, entries));

		// Table artifacts live as csv files beside the transcript, not in it.
		const mediaDir = join(sessionsDir, 'media', sessionId);
		for (const csvFile of [...(await listFiles(mediaDir, '.csv'))].sort()) {
			const name = basename(csvFile);
			let createdAt: string;
			try {
				createdAt = (await stat(csvFile)).mtime.toISOString();
			} catch {
				continue;
			}
			lines.push({
				id: `${sessionId}:${name}`,
				kind: 'table',
				sessionId,
				...(projectId !== undefined ? { projectId } : {}),
				// storeSessionTableCsv names files `<sanitized-title>-<hash8>.csv`.
				title: name.replace(/-[0-9a-f]{8}\.csv$/, '') || name,
				createdAt,
				payload: { type: 'media', path: csvFile },
			});
		}
	}

	if (lines.length > 0) {
		await mkdir(dirname(file), { recursive: true });
		await writeFile(file, `${lines.map(line => JSON.stringify(line)).join('\n')}\n`, 'utf8');
	}
	if (preserved.length > 0) {
		await mkdir(dirname(file), { recursive: true });
		await appendFile(file, `${preserved.join('\n')}\n`, 'utf8');
	}
}

/** Rewrite the scope's index without the deleted session's lines (patch lines match by their `<sessionId>:` id prefix). */
export async function removeSessionArtifacts(root: string, ref: { readonly sessionId: string; readonly projectId?: string }): Promise<void> {
	const file = artifactsFilePath(root, ref.projectId);
	let raw: string;
	try {
		raw = await readFile(file, 'utf8');
	} catch {
		return;
	}
	const kept = raw.split('\n').filter(line => {
		if (line.trim().length === 0) {
			return false;
		}
		try {
			const parsed = JSON.parse(line) as Record<string, unknown>;
			return parsed['sessionId'] !== ref.sessionId && !(typeof parsed['id'] === 'string' && parsed['id'].startsWith(`${ref.sessionId}:`));
		} catch {
			return false;
		}
	});
	if (kept.length === 0) {
		await rm(file, { force: true });
		return;
	}
	await writeFile(file, `${kept.join('\n')}\n`, 'utf8');
}

async function listFiles(dir: string, extension: string): Promise<readonly string[]> {
	try {
		const entries = await readdir(dir, { withFileTypes: true });
		return entries.filter(entry => entry.isFile() && entry.name.endsWith(extension)).map(entry => join(dir, entry.name));
	} catch {
		return [];
	}
}

async function listDirectories(dir: string): Promise<readonly string[]> {
	try {
		const entries = await readdir(dir, { withFileTypes: true });
		return entries.filter(entry => entry.isDirectory()).map(entry => entry.name);
	} catch {
		return [];
	}
}
